#!/usr/bin/env node
/**
 * @file Register the `x-socketsecurity--fleet://` URL scheme with the OS so a
 *   click on a fleet OSC-8 hyperlink reaches `fleet-url-action.mts`. Without
 *   this, the statusline's caret and copy links render but do nothing when
 *   clicked — the terminal opens the URL, the OS has no handler, and the click
 *   is lost.
 *   macOS: a minimal .app bundle at ~/.socket/app/fleet-url-handler.app/ with a
 *   CFBundleURLTypes entry. The bundle's executable is a shell script that runs
 *   `node <fleet-url-action.mts> <url>`, so the handler is always the current
 *   fleet script, not a frozen copy. Re-run after a fleet checkout move to
 *   re-point the executable at the new path.
 *   Linux and Windows: not yet implemented. A .desktop file with
 *   `x-scheme-handler/x-socketsecurity--fleet` or a Windows registry shim would
 *   reuse the same `fleet-url-action.mts` entry point.
 *   Usage: node scripts/fleet/setup/url-scheme.mts.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { spawnSync } from '@socketsecurity/lib-stable/process/spawn/child'

import { isMainModule } from '../process/is-main-module.mts'
import { REPO_ROOT } from '../paths.mts'
import { runMain } from '../process/run-main.mts'

import type { ScriptMeta } from '../process/run-main.mts'

const logger = getDefaultLogger()

const SCHEME = 'x-socketsecurity--fleet'
const BUNDLE_ID = 'dev.socket.fleet-url-handler'
const APP_DIR = path.join(
  os.homedir(),
  '.socket',
  'app',
  'fleet-url-handler.app',
)

/**
 * The shell script that the .app bundle runs. Resolves `fleet-url-action.mts`
 * from the repo root at click time, so a fleet checkout move needs no
 * re-registration — only a re-run of this setup script to re-point the
 * executable.
 */
function handlerScript(repoRoot: string): string {
  const script = path.join(repoRoot, 'scripts', 'fleet', 'fleet-url-action.mts')
  return `#!/bin/sh
# Auto-generated by scripts/fleet/setup/url-scheme.mts — do not edit.
# Routes an x-socketsecurity--fleet:// URL click to the fleet handler.
exec node '${script}' "$1"
`
}

/**
 * The Info.plist that registers the URL scheme with macOS Launch Services.
 */
function infoPlist(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>${BUNDLE_ID}</string>
  <key>CFBundleName</key>
  <string>Fleet URL Handler</string>
  <key>CFBundleExecutable</key>
  <string>fleet-url-handler</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key>
      <string>${BUNDLE_ID}</string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>${SCHEME}</string>
      </array>
    </dict>
  </array>
  <key>LSUIElement</key>
  <true/>
</dict>
</plist>
`
}

/**
 * Register the URL scheme on macOS by writing a minimal .app bundle and
 * re-registering with Launch Services.
 */
export function registerMacos(): boolean {
  const contents = path.join(APP_DIR, 'Contents')
  const macosDir = path.join(contents, 'MacOS')
  mkdirSync(macosDir, { recursive: true })

  const execPath = path.join(macosDir, 'fleet-url-handler')
  writeFileSync(execPath, handlerScript(REPO_ROOT), { mode: 0o755 })

  writeFileSync(path.join(contents, 'Info.plist'), infoPlist())

  // Re-register with Launch Services so the scheme takes effect immediately
  // rather than after a logout. Best-effort: lsregister is always at this path
  // on macOS, but swallowing the error keeps the setup fail-soft.
  try {
    spawnSync(
      '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister',
      [APP_DIR],
    )
  } catch {
    // lsregister missing or failed — the bundle is in place, so a logout/login
    // still picks it up.
  }
  return true
}

export async function main(): Promise<number> {
  if (process.platform !== 'darwin') {
    logger.log(
      `URL scheme registration for ${SCHEME} is not yet implemented for ${process.platform}.`,
    )
    return 0
  }
  if (
    !existsSync(
      path.join(REPO_ROOT, 'scripts', 'fleet', 'fleet-url-action.mts'),
    )
  ) {
    logger.fail(
      `fleet-url-action.mts not found at ${REPO_ROOT}. Run after a fleet fetch.`,
    )
    return 1
  }
  registerMacos()
  logger.success(
    `Registered ${SCHEME}:// → fleet-url-action.mts. Clicks on statusline links now work.`,
  )
  return 0
}

const SCRIPT_META: ScriptMeta = {
  describe:
    'register the x-socketsecurity--fleet:// URL scheme with the OS so statusline links are clickable',
  help: `Usage: node scripts/fleet/setup/url-scheme.mts

Writes a minimal .app bundle at ~/.socket/app/fleet-url-handler.app/ and
registers it with macOS Launch Services. The bundle routes URL clicks to
scripts/fleet/fleet-url-action.mts, which advances the model or copies text.

Re-run after moving the fleet checkout so the executable points at the new path.`,
}

if (isMainModule(import.meta.url)) {
  runMain(main, SCRIPT_META)
}
