#!/usr/bin/env node
/*
 * @file Gate: no source file points at a loose `.config/<file>.json`.
 *
 *   `.config/` is segregated into `.config/fleet/` (cascaded, fleet-owned) and
 *   `.config/repo/` (member-owned). A loose path in between names a file no
 *   repo carries, and the failure is SILENT: whoever reads that path gets
 *   nothing, the caller treats nothing as "no work to do", and the code looks
 *   like it ran.
 *
 *   Measured: the oxlint rule-activation fixer targeted a loose rc, so its
 *   autofix returned false for every member while the paired check kept
 *   reporting the same findings. A dead path throws nothing, so no test noticed.
 *
 *   The edit-time twin is `.claude/hooks/fleet/config-refs-are-segregated-at-edit/`,
 *   whose matchers this gate imports so the two cannot disagree about what
 *   counts. The hook stops a NEW one at the keystroke; this catches what is
 *   already committed. The corpus is clean, so the gate carries no allowlist:
 *   any finding is a real dead path.
 *
 *   Usage: node scripts/fleet/check/config-refs-are-segregated-at-commit.mts [--json]
 */

import { readFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { normalizePath } from '@socketsecurity/lib-stable/paths/normalize'

import { LOOSE_CONFIG_PATTERNS } from '../../../.claude/hooks/fleet/config-refs-are-segregated-at-edit/index.mts'
import { gitSync } from '../_shared/git-exec.mts'
import { isMainModule } from '../_shared/is-main-module.mts'
import { runMain } from '../_shared/run-main.mts'
import { REPO_ROOT } from '../paths.mts'

import type { ScriptMeta } from '../_shared/run-main.mts'

const logger = getDefaultLogger()

/**
 * The file kinds a loose reference can hide in. Markdown is excluded: prose
 * documenting the segregation has to be able to spell the shape it forbids.
 */
const SCANNED_EXTENSIONS: readonly string[] = ['.cjs', '.mjs', '.mts', '.ts']

/**
 * A test drives paths as DATA: a fixture writes one into a temp dir, and
 * several of these tests exist to assert behavior ABOUT a loose path (the
 * guard that blocks one, the check that finds one). Scanning them would flag
 * the fixtures those tests are made of.
 */
export function isTestPath(relPath: string): boolean {
  const unixPath = normalizePath(relPath)
  return (
    unixPath.startsWith('test/') ||
    unixPath.includes('/test/') ||
    unixPath.endsWith('.test.mts')
  )
}

/**
 * Files whose whole job is naming the loose shape: the hook that blocks it,
 * this gate, their tests, and the burn-down module explaining the debt.
 */
const SELF_REFERENTIAL: readonly string[] = [
  'config-refs-are-segregated-at-commit',
  'loose-config-ref-burn-down',
  'config-refs-are-segregated-at-edit',
]

/**
 * The committed dep-0 seed, generated by the bootstrap bundler. Generated
 * output is never gated, and the bundler strips comments, so a per-line escape
 * in the SOURCE cannot survive into the bundle: gating it would report a
 * finding whose only fix is to edit a generated file.
 */
const GENERATED_SEEDS: readonly string[] = ['scripts/repo/bootstrap/fleet.mjs']

export interface LooseRefFinding {
  readonly file: string
  readonly line: number
  readonly text: string
}

/**
 * The per-line escape, for the one legitimate shape: a MIGRATION READ that
 * probes the legacy location on a member that has not moved its config yet.
 * Dropping that probe makes the old file unreadable rather than migrated, so
 * the reference is correct and the marker records why. A WRITE never qualifies
 * — the new location is the only place anything is written.
 */
const ALLOW_MARKER_RE = /loose-config-ref:\s*allow\b/

export function isScannedFile(relPath: string): boolean {
  const unixPath = normalizePath(relPath)
  if (
    isTestPath(unixPath) ||
    GENERATED_SEEDS.some(seed => unixPath.endsWith(seed)) ||
    SELF_REFERENTIAL.some(name => unixPath.includes(name))
  ) {
    return false
  }
  return SCANNED_EXTENSIONS.some(ext => unixPath.endsWith(ext))
}

/**
 * Every loose reference in one file's text, as 1-indexed lines. CRLF is
 * normalized first so a Windows checkout does not leave a `\r` on every match.
 */
export function scanText(text: string, file: string): LooseRefFinding[] {
  const findings: LooseRefFinding[] = []
  const lines = text.replaceAll('\r\n', '\n').split(/\r?\n/)
  for (let i = 0, { length } = lines; i < length; i += 1) {
    const line = lines[i]!
    if (ALLOW_MARKER_RE.test(line)) {
      continue
    }
    if (LOOSE_CONFIG_PATTERNS.some(pattern => pattern.test(line))) {
      findings.push({ file, line: i + 1, text: line.trim().slice(0, 120) })
    }
  }
  return findings
}

/**
 * Scan every tracked source file.
 */
export function scanRepo(
  options?: { root?: string | undefined } | undefined,
): LooseRefFinding[] {
  const { root = REPO_ROOT } = { __proto__: null, ...options } as NonNullable<
    typeof options
  >
  // gitSync returns the spawnSync result, so stdout comes off the record and
  // may be a Buffer depending on the caller's stdioString setting.
  const listed = String(gitSync(['ls-files'], { cwd: root }).stdout ?? '')
  const tracked = listed
    .replaceAll('\r\n', '\n')
    .split(/\r?\n/)
    .filter(Boolean)
    .map(normalizePath)
  const findings: LooseRefFinding[] = []
  for (let i = 0, { length } = tracked; i < length; i += 1) {
    const rel = tracked[i]!
    if (!isScannedFile(rel)) {
      continue
    }
    let text: string
    try {
      text = readFileSync(path.join(root, rel), 'utf8')
    } catch {
      continue
    }
    findings.push(...scanText(text, rel))
  }
  return findings
}

function main(): number {
  const findings = scanRepo()
  if (process.argv.includes('--json')) {
    process.stdout.write(`${JSON.stringify({ findings }, undefined, 2)}\n`)
    return findings.length === 0 ? 0 : 1
  }
  if (findings.length === 0) {
    logger.log('every .config reference is segregated')
    return 0
  }
  {
    logger.fail(
      `${findings.length} loose \`.config/\` reference(s) point at a path no repo carries.`,
    )
    logger.group()
    for (const finding of findings) {
      logger.error(`${finding.file}:${finding.line}: ${finding.text}`)
    }
    logger.groupEnd()
    logger.error(
      '  Fix: point at `.config/fleet/<file>` (cascaded, fleet-owned) or `.config/repo/<file>` (member-owned). Never add a fallback branch.',
    )
  }
  return 1
}

const SCRIPT_META: ScriptMeta = {
  describe:
    'checks that no source file points at a loose .config/<file> path outside the fleet/ and repo/ tiers',
  help: 'Usage: node scripts/fleet/check/config-refs-are-segregated-at-commit.mts [--json]',
}

if (isMainModule(import.meta.url)) {
  runMain(main, SCRIPT_META)
}
