name: ⚡ CI

# Dependencies:
#   - SocketDev/socket-registry/.github/workflows/ci.yml

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Run CI Pipeline
    uses: SocketDev/socket-registry/.github/workflows/ci.yml@196b9f76f1f9b6dbc3ef958819f832a01f8a6294 # main
