name: Linting

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-check:
    uses: SocketDev/socket-registry/.github/workflows/lint.yml@main
    with:
      lint-script: 'pnpm run check-ci'
      node-version: '22'
      timeout-minutes: 10
