name: Linting

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-check:
    uses: SocketDev/socket-registry/.github/workflows/lint.yml@main
    with:
      lint-script: 'pnpm run check-ci'
      node-version: '22'
      timeout-minutes: 10
