name: 📦 Publish

# Dependencies:
#   - SocketDev/socket-registry/.github/workflows/provenance.yml

on:
  workflow_dispatch:
    inputs:
      dist-tag:
        description: 'npm dist-tag (latest, next, beta, canary, backport, etc.)'
        required: false
        default: 'latest'
        type: string
      debug:
        description: 'Enable debug output'
        required: false
        default: '0'
        type: choice
        options:
          - '0'
          - '1'

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: SocketDev/socket-registry/.github/workflows/provenance.yml@acfb0136c5c85334783e5e335a78b864e73f4fd9 # main (2026-05-15)
    with:
      debug: ${{ inputs.debug }}
      dist-tag: ${{ inputs.dist-tag }}
      package-name: '@socketregistry/packageurl-js'
      publish-script: 'publish:ci'
      setup-script: 'ci:validate'
      use-trusted-publishing: true
    secrets:
      SOCKET_API_TOKEN: ${{ secrets.SOCKET_API_TOKEN }}
