name: Tests

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    uses: SocketDev/socket-registry/.github/workflows/test.yml@main
    with:
      node-versions: '[20, 22, 24]'
      os-versions: '["ubuntu-latest", "windows-latest"]'
      setup-script: 'pnpm run build'
      test-script: 'pnpm run test-ci'
      timeout-minutes: 15
      fail-fast: false
      max-parallel: 4
