name: Type Checks

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  type-check:
    name: 'Type Check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: SocketDev/socket-packageurl-js/.github/actions/setup@7bbee47e4dbcce0c23237c2dd50f225487467ab3
        with:
          node-version: '22'

      - name: Run type check
        run: pnpm run check:tsc
