name: ⚙️ Types

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  types:
    uses: SocketDev/socket-registry/.github/workflows/types.yml@main
    with:
      node-version: '22'